### ISSUE TITLE
[Bug]: Телефон приходит со звездочками

### ISSUE THREAD

**Issue by LordOfTheApples123** [VKCOM/vkid-ios-sdk#12]
### Описание проблемы

Авторизация отрабатывает штатно. Токен и почта приходят в нормальном виде, а номер телефона приходит в формате "+7 *** *** ** 92". Данные организации в аккаунте подтверждены. И у приложения в кабинете выбран доступ для номер телефона.
id аккаунта 52649
id приложения 51840063

### Версия VK ID SDK

1.2.0

### Способ установки

CocoaPods

### Версия Xcode

15.0.1 (15A507)

### Версия iOS

17.0

**Comment by cocavo** [comment]
@LordOfTheApples123 

Да, подтверждаем наличие данной проблемы. Выпустили релиз с фиксом - [1.2.1](https://github.com/VKCOM/vkid-ios-sdk/releases/tag/1.2.1)

Спасибо за обращение!
