### ISSUE TITLE
[Feature]: Support App Privacy Manifest

### ISSUE THREAD

**Issue by sylvia-tencent-wmt** [VKCOM/vkid-ios-sdk#15]
### Цели

At WWDC23, Apple introduced a new Privacy Manifest and signatures for SDKs. 
I would like to know when you plan to adopt these changes, considering Apple's deadline in Spring 2024.

References:
* [Apple Developer News](https://developer.apple.com/news/?id=r1henawx)
* [Third-party SDK Requirements](https://developer.apple.com/support/third-party-SDK-requirements/)
* [Describing Use of Required Reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

Could you please provide information on your adoption timeline for these updates? Thank you.

### Описание/Детали реализации

Describe the solution you'd like
- Add Privacy Manifest
- Describing the use of required reason API

**Comment by cocavo** [comment]
Hi, @sylvia-tencent-wmt! Thanks that you pointed it out.

## Signatures of SDKs
According to Apple's [docs](https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks), xcframeworks' signatures are only required for binary SDKs. Our SDK is distributed as source code, so it seems, that the signature is not needed in this case. This [thread](https://developer.apple.com/forums/thread/739227) is also quite useful. 

## Privacy Manifest and Apple's deadline in Spring 2024
If our understanding of [Apple's requirements](https://developer.apple.com/support/third-party-SDK-requirements/) is correct, **Privacy Manifest** is recommended but not required for all third party libraries for now. **Privacy Manifest** is only required for the most popular SDKs as well as any SDKs that repackage those on the list at the bottom of this [article](https://developer.apple.com/support/third-party-SDK-requirements/). 

Anyway we are planning to adopt **Privacy Manifest** in our future releases.

**Comment by dbartsch-bf** [comment]
Hi @cocavo! Just wanted to ask if there have been any updates since February because we are also in the process
of updating our SDKs to fulfill the guidelines from Apple. Can you already say when we can expect
a new SDK release which includes the privacy manifest file?

**Comment by cocavo** [comment]
Hi @sylvia-tencent-wmt @dbartsch-bf. We've released [2.1.0](https://github.com/VKCOM/vkid-ios-sdk/releases/tag/2.1.0) which includes Privacy Manifest file.
