### ISSUE TITLE
[Bug]: Странное поведение при авторизации на устройстве с установленным приложением VK.

### ISSUE THREAD

**Issue by shizopudge** [VKCOM/vkid-ios-sdk#18]
### Описание проблемы

Привет, пишу плагин для Flutter.

При вызове метода authorize меня сначала редиректит в приложение VK, в нем я авторизируюсь. После авторизации в приложении VK меня редиректит в мое приложение и запрашивает разрешение использовать "vk.com" для входа, чтобы снова авторизироваться. Я авторизируюсь и получаю данные. Авторизация происходит только 1 раз и все ок, но правильное ли это поведение?

Кажется, что после авторизации в приложении VK меня просто должно вернуть в приложение и отдать данные.

### Шаги для воспроизведения

1. Установить VK на устройство.
2. Попробовать авторизироваться с помощью VK ID IOS SDK.

### Версия VK ID SDK

1.3.0

### Способ установки

CocoaPods

### Версия Xcode

15.3

### Версия iOS

17.4.1

**Comment by cocavo** [comment]
Привет! Сейчас перепроверим на своей стороне.

**Comment by cocavo** [comment]
@shizopudge Можете, пожалуйста, проверить, что корректно обрабатываете открытие ссылки при возврате в ваше приложение из провайдера? Нужно обязательно вызвать `vkid.open(url:)` в соответствующем методе `UIApplicationDelegate` либо `UISceneDelegate`. Подробнее можно посмотреть [здесь](https://github.com/VKCOM/vkid-ios-sdk?tab=readme-ov-file#базовая-авторизация).

**Comment by shizopudge** [comment]
@cocavo Большое спасибо за оперативный ответ! Похоже я упустил этот момент... Сегодня исправить уже не получиться, завтра внесу изменения и опишу результат.

**Comment by shizopudge** [comment]
@cocavo Привет, добавил обработку ```vkid.open(url:)``` и все заработало корректно. Спасибо!
