### ISSUE TITLE
Некорректное поведение при авторизации через приложение

### ISSUE THREAD

**Issue by Treisy-dev** [VKCOM/vkid-ios-sdk#27]
### Описание проблемы

Я пишу приложение на SwiftUI и хочу добавить авторизацию через ВКонтакте.
При авторизации из приложения происходит перенаправление в приложение ВКонтакте, там авторизируемся и наблюдаем первую проблему - нерабочий переход по UniversalLink. (Нет перенаправления обратно в приложение).
Если указать в info.plist URLTypes в виде vk12345678, то переход обратно сработает, однако авторизация не выполнится и попросит открыть "vk.com" для входа, где авторизация сработает корректно. В другом issue видел подобный вопрос где проблема решилась прописыванием vkid.open(url:url) в AppDelegate. Данная проверка у меня есть, а с помощью
```
 .onOpenURL { url in
  print("Opened URL: \(url)")
}
```
Я вижу что мне возвращается url с данными пользователя:
"vk12345678://?payload=%7B%22type%22%3A%22oauth%22%2C%22auth%22%3A1%2C%22user%22%3A%7B%22id%22%3A307011254%2C%22first_name%22%3A%22%D0%9A%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%22%2C%22last_name%22%3A%22%D0%A9.%22%2C%22avatar%22%3A%22https%3A%5C%2F%5C%2Fsun36-1.userapi.com%5C%2Fs%5C%2Fv1%5C%2Fig2%5C%2FbtxfCp7YbAhoHP1yuFQW4hRWlvBlMpFgocY2xgV3Gow5gB4jwHDjJKSqboMz39Hawc3teeKhdkH5d_3-eczz97aw.jpg%3Fsize%3D200x200%26quality%3D96%26crop%3D427%2C0%2C1706%2C1706%26ava%3D1%22%2C%22avatar_base%22%3Anull%2C%22phone%22%3A%22%2B7%20%2A%2A%2A%20%2A%2A%2A%20%2A%2A%2085%22%7D%2C%22ttl%22%3A600%2C%22uuid%22%3A%22BFC0717B-9EDB-4054-BCDD-2D4391F43A27%22%2C%22hash%22%3A%22R4mDrmKiBsunBZd1QWUYcvqem83Ha6X16nIF3iyRGUL%22%2C%22oauth%22%3A%7B%22code%22%3A%22ac927cfb60e8a81dcd%22%2C%22state%22%3A%22CF9A9A0C-9AEB-490C-BED3-1E33493191E3%22%2C%22oauth_response_type%22%3A%22code%22%2C%22oauth_code_challenge%22%3A%22%22%2C%22oauth_code_challenge_method%22%3A%22%22%7D%7D&state=CF9A9A0C-9AEB-490C-BED3-1E33493191E3&vkconnect_auth_provider_method=external_auth"

однако метод authorize не может получить результат (result.get()) и падает в catch.

### Шаги для воспроизведения

Установить VK на устройство.
Попробовать авторизироваться с помощью VK ID IOS SDK.

### Версия VK ID SDK

1.3.2

### Способ установки

Swift Package Manager

### Версия Xcode

15.4

### Версия iOS

14+

**Comment by Treisy-dev** [comment]
да, я так и сделал и это помогло. Но только есть вопрос, почему vkid.open(url: url) возвращает Bool? (Не понимаю для чего это тогда).
Спасибо вам за оперативный ответ. Если есть такая возможность добавьте упоминание данного метода в инструкцию по VKID. (Инструкция и документация хорошие, но без issue на gitHub не работает =) )

**Comment by cocavo** [comment]
> Но только есть вопрос, почему vkid.open(url: url) возвращает Bool? (Не понимаю для чего это тогда).

Чтобы можно было определить, что переденный `url` валидный и успешно обработан `vkid`: 
- `true` указанный `url` валидный и успешно обработан для получения авторизации
- `false` указанный `url` невалидный для авторизации и вы можете его обработать на своей стороне. Например если вы используете еще какую то авторизацию от другого сервиса.

> Если есть такая возможность добавьте упоминание данного метода в инструкцию по VKID. (Инструкция и документация хорошие, но без issue на gitHub не работает =) )

Да, обязательно дополним документацию. Спасибо за отзыв!
