### ISSUE TITLE
Не приходит информация о юзере

### ISSUE THREAD

**Issue by Levin-nik** [VKCOM/vkid-ios-sdk#6]
Здравствуйте.

Подключаем VKID-sdk на android и ios

При авторизации через `vkid-android-sdk`, приходит информация о юзере, здесь приходит только accessToken и userId

Подскажите как я могу получить информацию о пользователе или будет доработка пакета?

**Comment by cocavo** [comment]
Здравствуйте!

Данная доработка сейчас в процессе, обязательно включим ее в ближайший релиз.

**Comment by cocavo** [comment]
@Levin-nik Выпустили версию [1.2.0](https://github.com/VKCOM/vkid-ios-sdk/releases/tag/1.2.0). Там информация о пользователе должна приходить после авторизации.
